
package com.pfgc.wsclient.productcardinfo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductCardInfo", targetNamespace = "http://www.pfgc.com/ProductCardInfo", wsdlLocation = "http://njdcwebmqp1:7800/GetProductCardInfo?wsdl")
public class ProductCardInfo_Service
    extends Service
{

    private final static URL PRODUCTCARDINFO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pfgc.wsclient.productcardinfo.ProductCardInfo_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pfgc.wsclient.productcardinfo.ProductCardInfo_Service.class.getResource(".");
            url = new URL(baseUrl, "http://njdcwebmqp1:7800/GetProductCardInfo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://njdcwebmqp1:7800/GetProductCardInfo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODUCTCARDINFO_WSDL_LOCATION = url;
    }

    public ProductCardInfo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCardInfo_Service() {
        super(PRODUCTCARDINFO_WSDL_LOCATION, new QName("http://www.pfgc.com/ProductCardInfo", "ProductCardInfo"));
    }

    /**
     * 
     * @return
     *     returns ProductCardInfo
     */
    @WebEndpoint(name = "ProductCardInfoSOAP")
    public ProductCardInfo getProductCardInfoSOAP() {
        return super.getPort(new QName("http://www.pfgc.com/ProductCardInfo", "ProductCardInfoSOAP"), ProductCardInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCardInfo
     */
    @WebEndpoint(name = "ProductCardInfoSOAP")
    public ProductCardInfo getProductCardInfoSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.pfgc.com/ProductCardInfo", "ProductCardInfoSOAP"), ProductCardInfo.class, features);
    }

}
