
package com.pfgc.wsclient.productcardinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductCardInfo", targetNamespace = "http://www.pfgc.com/ProductCardInfo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCardInfo {


    /**
     * 
     * @param productCardRequest
     * @return
     *     returns com.pfgc.wsclient.productCard.ProductCardResponse
     */
    @WebMethod(operationName = "GetProductCardInfo", action = "http://www.pfgc.com/ProductCardInfo")
    @WebResult(name = "ProductCardResponse", targetNamespace = "http://www.pfgc.com/ProductCardInfo", partName = "ProductCardResponse")
    public ProductCardResponse getProductCardInfo(
        @WebParam(name = "ProductCardRequest", targetNamespace = "http://www.pfgc.com/ProductCardInfo", partName = "ProductCardRequest")
        ProductCardRequest productCardRequest);

}
